# Configuration file
# key = value

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${QUARKUS_USERNAME}
quarkus.datasource.password=${QUARKUS_PASSWORD}
quarkus.datasource.jdbc.url=${QUARKUS_JDBC_URL}?currentSchema=invoice

quarkus.datasource.health.enabled=true
quarkus.log.level=OFF